sources:
  - title: GONG
    links:
      - https://gong.hr/
  - title: Popravi to
    links:
      - https://popravi.to/
  - title: Public Money Public Code
    links:
      - https://pmpc.hr/
  - title: Code For Croatia
    links:
      - https://codeforcroatia.org/
  - title: Predizborna obećanja
    links:
      - https://lookerstudio.google.com/u/0/reporting/cab3e2df-5406-4b30-aa84-244d60361a88/page/ssaoD
      - https://docs.google.com/spreadsheets/d/1wo_D2bJji_Sbq_tmuvOIlzbSst7Mbl5_TjoB769xVLI/edit?gid=0
  - title: Parlametar Sabora
    links:
      - https://parlametar.hr/
  - title: Izborni Simulator
    links:
      - https://izbornisimulator.azurewebsites.net/
  - title: Grad Zagreb
    links:
      - https://smart.zagreb.hr/
      - https://geoportal.zagreb.hr/
      - https://geohub-zagreb.hub.arcgis.com/
      - https://zagreb.gdi.net/zg3d/
  - title: Državni Portal Otvorenih Podataka
    links:
      - https://data.gov.hr/
  - title: Mozaik Veza - Veze Politički Izloženih Osoba
    links:
      - https://www.mozaikveza.hr/
  - title: Slobodna Domena - Zadruga Za Otvoreni Kod I Dizajn
    links:
      - https://slobodnadomena.hr/
  - title: Zelena Akcija
    links:
      - https://www.zelena-akcija.hr/hr
  - title: Pametni Zeleni Telefon
    links:
      - https://zelena-akcija.hr/hr/vijesti/predstavljena-nova-aplikacija-pametni-zeleni-telefon
  - title: ZET Info
    links:
      - https://zet-info.com/
  - title: Mreža Antifašistkinja Zagreb
    links:
      - https://www.maz.hr/
    socials:
      facebook: https://web.facebook.com/antifamrezazg
  - title: Kartografija otpora
    links:
      - https://www.kartografija-otpora.org/hr/
  - title: Sindikat biciklista
    links:
        - https://sindikatbiciklista.hr/
    socials:
      facebook: https://web.facebook.com/sindikatbiciklista